apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
data:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:1BgyOq70,iv:NfnNrrJK/oDCHiqaMsSJXtnwM88P3hEtI+CUU1YYj2A=,tag:BtbszbFxWebEf+8/ZvSZOQ==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:s/xEx48zXc4=,iv:5owr20RRwSzAQ/GZ/cI+5IY3Rg7IgmfJYYMe/hsaXkc=,tag:ep0x0cjqAZ4hihWYY/t2kg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T17:16:46Z"
    mac: ENC[AES256_GCM,data:+bPQOfDS9CfoAILm4VEn9lWl/TiAkBB4p8X9hA1JAF81dVNGRUrGHZOm6xeFk3qeq21oGtzWrtxdikmXt3c8Zc3+0oUl9fJ7K4bwtMRaqpSg9o2JdPaEIMaFGxRH0k5fk/KVuYlKCHMsibcWNtccPT3rsC0L/6oMXiD46DUCaOM=,iv:rJvgduEFZCg6Lhlj98CtkzMwXVijvoUN7IhWvjKyEMg=,tag:TOKg889FxfD62JCKT4W0iQ==,type:str]
    pgp:
        - created_at: "2026-08-29T16:28:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DqZZ7x0dZaOcSAQdArbQCGbwakl9IttK5bXlrIeS55oU+jKRBO4Rb2BhmIzMw
            3MT/TluGRaUtl5+ebWIdgz90Lm/DIV0bvhqFAZpfBOehrH+XbeQUdsGNQI4G5btR
            1GgBCQIQRNU8fw57PErjq6sqj7ETQjCRq9QLgpsKsvYVWOkeJj5ZhwzETLSMNLfp
            WbuQae2t2/Y9Bfe+lVcqngdvsb4Uz1NnD+Ov72MPlKVqCMZJdc2dkfNjfn11XBmv
            DjhpCwZcHOyVZA==
            =knuj
            -----END PGP MESSAGE-----
          fp: 657779F272AC9A0CC049A72C4A7CFAE00AE57FE4
    version: 3.13.3
