apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
data:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:1BgyOq70,iv:NfnNrrJK/oDCHiqaMsSJXtnwM88P3hEtI+CUU1YYj2A=,tag:BtbszbFxWebEf+8/ZvSZOQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T16:28:36Z"
    mac: ENC[AES256_GCM,data:1fQAC5bvFsRmwNoDT0cGSzHpYXZHgXT9+PhnhBhW8t9jQ9LbtTT9+3MM7EmUtx/GMzG6PJ7gJCiC0y3ZvWZAHf8i49HrNSyog0Demq5jEzSkgJ5YYueFf1uQXrQRdfQKtjRKqrhGyFUHleR2OAMjsqf5c+FuLp5rFs5bLCNku6E=,iv:Y4RXdACGVrUEaNSXVn6+Xn7t0RxuD22RkB/RmMuwswA=,tag:frgBNvtoapPMDkcyn9yEiA==,type:str]
    pgp:
        - created_at: "2026-08-29T16:28:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DqZZ7x0dZaOcSAQdArbQCGbwakl9IttK5bXlrIeS55oU+jKRBO4Rb2BhmIzMw
            3MT/TluGRaUtl5+ebWIdgz90Lm/DIV0bvhqFAZpfBOehrH+XbeQUdsGNQI4G5btR
            1GgBCQIQRNU8fw57PErjq6sqj7ETQjCRq9QLgpsKsvYVWOkeJj5ZhwzETLSMNLfp
            WbuQae2t2/Y9Bfe+lVcqngdvsb4Uz1NnD+Ov72MPlKVqCMZJdc2dkfNjfn11XBmv
            DjhpCwZcHOyVZA==
            =knuj
            -----END PGP MESSAGE-----
          fp: 657779F272AC9A0CC049A72C4A7CFAE00AE57FE4
    version: 3.13.3
