apiVersion: v1
data:
    PAPERLESS_REDIS: ENC[AES256_GCM,data:IjK7bxdhuoI=,iv:9JAm2jv6XwNvxPc/CL17F2oSHRflPSNy3QAV3wYFnWE=,tag:aMks5kpHBojP6x/ySQXkpw==,type:str]
kind: Secret
metadata:
    name: paperless-secret
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T15:18:01Z"
    mac: ENC[AES256_GCM,data:FmIhHdOVOqUjfzTmyy85VJbuPwa2AiXncnWbMjS3el0kHFFIK3TOyFoC7fDwbmo8OsnAA4DwzEBlrUR1mjDlOL3mbjfGq/pU8yAJT1qbL4JTHq6QoVBbygVAEO6OuNZgayDRXQD0fdxh472ErSH5gtklyrap0ksaRCj1KNoOll8=,iv:ZH7aO1gOmELmzPmcwd8czMo5AhKdZaYBgAiftLmbcR4=,tag:YKQZrKCA/fWOQXPxJ9blLQ==,type:str]
    pgp:
        - created_at: "2026-08-31T15:18:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DqZZ7x0dZaOcSAQdAIUdzQnUJpdFYCHb/LOlUa9rPBKfQ7u8MoOFcPFK1bjIw
            B08x7kSFuQcnKpnpFjGnRD5KFV03jOsNStQnJZSatQ9IocENCki0OyPjfotfJvpK
            1GgBCQIQA053q7OsicBuHS6PM8L02eL+0WBEFY5DM869TGHC8Nz6BYS+OULsBkAy
            ikjUhXTx3L4gSqQqStW4NAwptFB6RKPr+DS2wo6+CBz/qmDo1vLC2xZDpC60fCPP
            PQtcYphu4IlQ1g==
            =cU3b
            -----END PGP MESSAGE-----
          fp: 657779F272AC9A0CC049A72C4A7CFAE00AE57FE4
    version: 3.13.3
