apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:J+CWFUdjXbg=,iv:Wc9LlAOxaEtDkSm1gRaya/Z1UzOYOhI/z2MFY9KrgAg=,tag:H502hOolh8zw7OSiJ4VTng==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:XurIqaVOqpA=,iv:qqMrQpRClz9GmfMDBZHgpspR1WeyCr5okCCHccj8d1g=,tag:SAUBUMzMQdV2oqhmA7EQSg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T16:11:31Z"
    mac: ENC[AES256_GCM,data:+4SXr1b4nM1WuqOek+s1UM/xNPmo1+kC6rXC+lr16KKopJRi5T6B344TNJ4miO2ceJ/02c5tZc0emDElcrzBEBmwxgn+hWvEiFC/Gioig6dX4k8lUb64YndyRMqsgfcRynEg1MpI/qapvdZPxDGLHcPdiiWeTLbtPTFtn9tArKA=,iv:RHnDpCu3GZfXU2QBHB7xSFlxWDC7QUSJ2Ql0Tf0at5U=,tag:8hHNJLj2V/s67HtbuldK7A==,type:str]
    pgp:
        - created_at: "2026-08-31T16:11:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYg/7V2gORCkSAQdA7qiD5sXfw5TeqAR9xcylPpP391GmSzFrcdgOWgHwx2Qw
            N4ZKnXcIoVuom4TB3wpFqGfzMYSCoiZbL/5Shd1BUwvnJ7dW46Li6Z7mNE87cfeC
            1GYBCQIQtn+eFeuj5YD+sw9c8ynGnFxdG09wTkaGjXbT6cDNXhRG4P1HlFzAx25Z
            mXk2GBuFxKhUn27of9oK8fnY8eqiwdAFxJdS2CiKqex88yA2/O/Pz7NvKY7YC1g8
            MwDEle+jbCA=
            =YqN1
            -----END PGP MESSAGE-----
          fp: 5A79DC9085E8398E5581CEC7FFB0ACBE6384DD27
    version: 3.13.3
