apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: postgres
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:5K4FyWw+Q7M=,iv:hRm6GHKOg7oERgFccJskv8QhyLVwlZvvppgjwqfDi7I=,tag:hxB7mW7CVk6kMJ0DfnlAQw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T17:21:29Z"
    mac: ENC[AES256_GCM,data:HNTXOdkDB+ZojrScHhnEfqWR+hFUoa1jUy6ijVCC5jzVnw9rthwMvzNvsl8COQ3kItZWP4RlkfCN2jqG6fCOcdKAD30AjZV6RxXfJZW/dXU+IXoLyE1pDLoS9ToNzxyMytbgO/+GX2xPDrWirgz7Dq/cDuYX+cmrjgfDbBLNvCA=,iv:X0Hv1+vwDJxWeV298WujI+ag1B74RFTJ0F1DV/dIPv8=,tag:vxnRR649bGl575M4wazYMg==,type:str]
    pgp:
        - created_at: "2026-08-29T17:20:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DqZZ7x0dZaOcSAQdAmWm66Cf50Vu9ErlrSJsyZ4eCwxvTM4osEEOlNYxQAiQw
            w3HnSZdQP3j3tXu7XsoVDLgHrCyCRHZNbrtX6DSHPhKRO2skpWhHMga4axfYCi5+
            1GYBCQIQoIas3Xyg4PLJDEovHlh0PCjAp+UKTVT1K1hplMCOp0j57VCPD1pYcnMB
            /YqLLbc4M1a1MXdj7eUiwIaPno6SnbAmfBE3rU34ZBdC8kccNXMp+oUQuap+sdHC
            icUPdgwLU2w=
            =vE9f
            -----END PGP MESSAGE-----
          fp: 657779F272AC9A0CC049A72C4A7CFAE00AE57FE4
    version: 3.13.3
