apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: postgres
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:z3Wkopat78E=,iv:820C70McjXTg5lxBNE91pZPHGTiypTtv0mcih7ezi9U=,tag:3cgebG19ako9Rzj0YJqcAQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T16:11:21Z"
    mac: ENC[AES256_GCM,data:9OR4j26ihf0Z6HbjmwdWZ7Lu9H2Wse0a14l+PhEgge8mr3kg5VysolPauMuRDk0mam0TVKedaQfCPSQfzFoq+HB/0kvS5ovnNQrsAvPBTNCI0GFRwSzIbNBWnUB9o1uDQ+NIGHG6Aj9kSsvmaI1Md+49MButaPhX2E52kis9KKk=,iv:eHtDGDFq+gwGJoJSCa6RHfhLz3wiZ7F7nuuuMEWZIDo=,tag:w+46d1kw1w4hZE3pd6VcNw==,type:str]
    pgp:
        - created_at: "2026-08-31T16:11:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYg/7V2gORCkSAQdA0Hyx2nG6dYQmWUG6O6tRIxaLGNPiZvm2b/5J/S+FzBww
            7lJEKscqaH69wL1MT8Lx57QAEQOa+t0xn7zEukwlfJLQmY9Fy4yWkKulVsAugxvs
            1GgBCQIQEUUbxvSvBs3MrfEZwIQPxdjGtiS5DqlD102vcQL8I8QbEuX78eak3oCg
            cN66ht/6dPGN4bfhohFO/N0ZIhHaglTwkLWI0+66wuqDWoDZcSA7a6EgKudfcTq7
            AQ8JvkleLs4D3A==
            =VFH5
            -----END PGP MESSAGE-----
          fp: 5A79DC9085E8398E5581CEC7FFB0ACBE6384DD27
    version: 3.13.3
