apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: mid-priority
preemptionPolicy: PreemptLowerPriority
value: 150000
description: "Mid tier workload, use this for general app, monitoring and db stuff"
