apiVersion: apps/v1
kind: Deployment
metadata:
  name: habit-deployment
  namespace: habit
  labels:
    app: habit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: habit
  template:
    metadata:
      labels:
        app: habit
    spec:
      imagePullSecrets:
      - name: ghcr-secret

      containers:
      - name: habit
        image: ghcr.io/florianbesson/habit-tracker-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
