apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: habit-data
  namespace: habit
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
